version: '3.9'

services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    ports:
      - 8081:8081
    volumes:
      - /data/metube:/downloads:rw
    healthcheck:
      test: curl -f http://localhost:8081/ || exit 1
    mem_limit: 6g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5